controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
home:
    path: /
    controller: App\Controller\HomeController::index
app_logout:
    path: /logout
    methods: GET